### PR TITLE
Potential fix/workaround for the grails-spring-security-core issue 554

### PR DESCRIPTION
**Pull request by ddelponte**
This may be a potential fix/workaround for the issue reported at http…s://github.com/grails-plugins/grails-spring-security-core/issues/554

Please test it out and let me know if it satisfies your requirements.

### CODE REVIEW

**Review by majaode — COMMENTED** [review]
Hit error when I try to change the secure annotation value at UserController from `@Secured(['permitAll'])` to `
@Secured(['isFullyAuthenticated()'])`

**Comment by ddelponte** [comment]
Would you provide the error details?

I would expect an error if you are not authenticated and make a PUT request to that endpoint while also excluding exception translation filters

**Comment by ddelponte** [comment]
FYI - I have a fix for this issue will publishing a PR in grails-spring-security-core soon

**Comment by ddelponte** [comment]
FYI - Here's the PR that will fix this issue:
https://github.com/grails-plugins/grails-spring-security-core/pull/557

**Pull request merged**
